allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
def rootProjectPath = rootProject.projectDir.canonicalPath
subprojects {
    def subprojectPath = project.projectDir.canonicalPath
    if (subprojectPath.startsWith(rootProjectPath)) {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    def setJvmTarget = {
        if (project.hasProperty('android')) {
            project.android {
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }
                if (project.android.hasProperty('kotlinOptions')) {
                    kotlinOptions {
                        jvmTarget = '17'
                    }
                }
            }
        }
    }
    if (project.state.executed) {
        setJvmTarget()
    } else {
        project.afterEvaluate {
            setJvmTarget()
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
